import { TenantConfig } from '@/types';

export const DEFAULT_TENANT: TenantConfig = {
  id: 'tenant-lugari',
  name: 'Lugari Digital Infrastructure',
  shortName: 'Lugari.ke',
  domain: 'lugari.ke',
  county: 'Kakamega County',
  country: 'Kenya',
  logo: '/logo.png',
  primaryColor: '#0f392b', // Deep forest green
  contact: {
    email: 'info@lugari.ke',
    phone: '+254 700 000 000',
    whatsapp: '+254 700 000 000',
    address: 'Lugari Sub-County Headquarters, Lumakanda, Kenya',
    officeHours: 'Mon - Fri: 8:00 AM - 5:00 PM EAT',
  },
  wards: [
    {
      id: 'ward-mautuma',
      name: 'Mautuma Ward',
      slug: 'mautuma',
      population: 34500,
      areaKm2: 82.5,
      headquarters: 'Mautuma Centre',
      description: 'Major agricultural hub known for maize production, dairy farming, and vibrant local trade centers.',
      representativeName: 'Hon. MCA Mautuma',
      representativeTitle: 'Member of County Assembly - Mautuma',
      representativeContact: '+254 712 111 222',
      coordinates: { lat: 0.6521, lng: 35.1245 },
    },
    {
      id: 'ward-lumakanda',
      name: 'Lumakanda Ward',
      slug: 'lumakanda',
      population: 41200,
      areaKm2: 74.2,
      headquarters: 'Lumakanda Sub-County HQ',
      description: 'The administrative heart of Lugari, hosting major public services, courts, and secondary institutions.',
      representativeName: 'Hon. MCA Lumakanda',
      representativeTitle: 'Member of County Assembly - Lumakanda',
      representativeContact: '+254 712 222 333',
      coordinates: { lat: 0.6215, lng: 35.0982 },
    },
    {
      id: 'ward-lugari',
      name: 'Lugari Ward',
      slug: 'lugari',
      population: 38900,
      areaKm2: 91.0,
      headquarters: 'Lugari Station',
      description: 'Historic railway and transit hub featuring extensive farming communities and youth sports initiatives.',
      representativeName: 'Hon. MCA Lugari',
      representativeTitle: 'Member of County Assembly - Lugari',
      representativeContact: '+254 712 333 444',
      coordinates: { lat: 0.5891, lng: 35.0714 },
    },
    {
      id: 'ward-chekalini',
      name: 'Chekalini Ward',
      slug: 'chekalini',
      population: 32100,
      areaKm2: 68.4,
      headquarters: 'Chekalini Market',
      description: 'Key agricultural ward with rich horticulture, sugarcane farming, and thriving micro-enterprises.',
      representativeName: 'Hon. MCA Chekalini',
      representativeTitle: 'Member of County Assembly - Chekalini',
      representativeContact: '+254 712 444 555',
      coordinates: { lat: 0.5432, lng: 35.0321 },
    },
    {
      id: 'ward-chevaywa',
      name: 'Chevaywa Ward',
      slug: 'chevaywa',
      population: 36700,
      areaKm2: 79.8,
      headquarters: 'Koromaiti',
      description: 'Known for high educational outcomes, active women groups, and sustainable smallholder farming.',
      representativeName: 'Hon. MCA Chevaywa',
      representativeTitle: 'Member of County Assembly - Chevaywa',
      representativeContact: '+254 712 555 666',
      coordinates: { lat: 0.5123, lng: 35.0112 },
    },
    {
      id: 'ward-lwandeti',
      name: 'Lwandeti Ward',
      slug: 'lwandeti',
      population: 29800,
      areaKm2: 62.3,
      headquarters: 'Lwandeti Centre',
      description: 'Strategic market zone connecting Lugari to Webuye Highway, rich in commercial transport and trades.',
      representativeName: 'Hon. MCA Lwandeti',
      representativeTitle: 'Member of County Assembly - Lwandeti',
      representativeContact: '+254 712 666 777',
      coordinates: { lat: 0.4812, lng: 34.9854 },
    },
  ],
  featureFlags: {
    marketplace: true,
    ussd: true,
    liveStreaming: true,
    politicalAds: false,
    talentDirectory: true,
    agriculture: true,
    aiSummaries: true,
    bursaries: true,
  },
};
